name: CI Pipeline

on:
  pull_request:
    types: [opened, reopened, edited, synchronize]

jobs: 
  build:
    runs-on: ubuntu-latest

    steps:

    #step1: checkout the code
      - name: Checkout code
        uses: actions/checkout@v5

      - name: confirm checkout  
        run: echo "Checkout Happening"

    #step2: setup node
      - name: Setup node
        uses: actions/setup-node@v5

    #initialize node
      - name: Initialize node
        run: npm init -y
        
    #step3: install any dependencies
      - name: Install dependencies
        run: npm install

    #step4: run ESlint
      - name: Run Lint
        run: npm run lint

    #step5: run prettier --write
      - name: Run Prettier
        run: npm run prettier

    #step6: run Jest
      - name: Run Jest
        run: npm run test

    #step7: Build
      - name: Build
        run: npm run build
